### ISSUE TITLE
Impressive work

### ISSUE THREAD

**Issue by mattallty** [HoldemPokerTools/RangeAssistant#62]
Impressive work, bravo and thanks for sharing!

Do you plan to provide typescript declarations for your web package ?
I'm considering integrating your web package, at least some components, into a larger upcoming web app

**Comment by HieronymusLex** [comment]
I haven't much experience with TS so I wasn't planning on it, but I'm more than happy to merge a PR for this?

**Comment by HieronymusLex** [comment]
Closing this as I’m not intending to add TS declaration but open to PRs
